name: repoman

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup master gentoo repository
        run: |
          ./scripts/setup-master-gentoo.sh
      - name: Setup and run repoman
        run: |
          ./scripts/setup-and-run-repoman.sh
